version: '3'

services:
  cosmos-testnet:
    container_name: cosmos-testnet
    build:
      context: .
      dockerfile: Dockerfile-testnet
    environment: 
      - MONIKER=NodeName
      - CHAIN_ID=gaia-13004
      - GENESIS_URL=https://raw.githubusercontent.com/cosmos/testnets/master/gaia-13k/genesis.json
      - SEEDS=17c443c877662296fd46f67b6a1a27a4821b996a@highfrequencystaking.com:26656
      - BOOTSTRAP=FALSE
      # - ADDR_BOOK_STRICT=false
      # - CACHE_SIZE=10000
    restart: always
    ports:
      - "26656:26656"
      - "26657:26657"
      - "26658:26658"
      - "1317:1317" # for rest-server
    volumes:
      - cosmos-testnet-data:/.gaiad
volumes:
  cosmos-testnet-data:
