version: '3'

services:
  docker-cosmos:
    container_name: ivy-mike
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - MONIKER=NodeName
      - CHAIN_ID=gaia-13003
      # - GAIAD_HOME=/.gaiad
      # - GENESIS_URL= comment out for default 13003 (give url for cosmoshub-2)
    ports:
      - "26656:26656"
      - "26657:26657"
      - "26658:26658"
      - "1317:1317" # for rest-server
    volumes:
      - ./data/config:/.gaiad/config
      - ./data/keys:/.gaiacli/keys

