version: '3'

services:
  cosmos-testnet:
    container_name: cosmos-testnet
    build:
      context: .
      dockerfile: Dockerfile-testnet
    environment: 
      - MONIKER=NodeName
      - CHAIN_ID=gaia-13005
      - GENESIS_URL=https://raw.githubusercontent.com/cosmos/testnets/master/latest/genesis.json
      - SEEDS=35b9658ca14dd4908b37f327870cbd5007ee06f1@116.203.146.149:26656, c24f496b951148697f8a24fd749786075c128f00@35.203.176.214:26656, 6be0856f6365559fdc2e9e97a07d609f754632b0@cosmos-gaia-13004-seed.nodes.polychainlabs.com:26656
      # - LCD_PORT=3317
      # - RPC_LADDR_PORT=36657
      # - CONNECTIONS_LADDR_PORT=36656
      # - PROXY_APP_PORT=36658
      # - BOOTSTRAP=FALSE
      # - CACHE_SIZE=50000
      - GAIAD_HOME=/.gaiad
      # - ADDR_BOOK_STRICT=false
      # - CACHE_SIZE=10000
    restart: always
    ports:
      - "26656:26656"
      - "26657:26657"
      - "26658:26658"
      - "1317:1317" # for rest-server
    volumes:
      - cosmos-testnet-data:/.gaiad
volumes:
  cosmos-testnet-data:
